version: 2
jobs:
    build_1:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "Hello world"
    build_2:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "Buenas noches America"
            
workflows:
    version: 2
    one_and_two:
        jobs:
            - build_1
            - build_2