version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
jobs:
    build_1: # this one job
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "Hello world"
            - run: mkdir -p my_workspace
            - run: echo "New feature" > my_workspace/echo-output
            - persist_to_workspace:
                root: my_workspace
                paths:
                    - echo-output
    build_2: # this another job
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: echo "Good morning everyone"
            - attach_workspace:
                at: my_workspace
            - run: |
                if [[ $(cat my_workspace/echo-output) == "New feature" ]]; then
                    echo "It worked!";
                else 
                    echo "Nope!"; exit 1
                fi
            - run: echo "My password is $password"
    build_3: 
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run: 
                name: "Test 3"
                command: sayhello
                
workflows:
    version: 2
    one_and_two: # here you can invoke any job, those will run parallel
        jobs:
            - build_1
            - build_2: 
                requires:
                    - build_1
    three:
        jobs:
            - build_3
                    
                    